# #server:
# #  port: 8000

# spring:

#   # konfigurasi untuk koneksi db
#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver

#     # sesuaikan nama database anda dengan di bawah ini
#     url: jdbc:mysql://containers-us-west-93.railway.app:6158/railway

#     # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
#     username: root
#     password: t2BpsZqxtQnjgxHplIkQ

#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#         format_sql: true

#     # pembuatan database (create || create-drop || validate || update)
#     hibernate.ddl-auto: update
#     show-sql: true


#   # Templates reloading during development
#   thymeleaf:
#     prefix: classpath:/templates/
#     suffix: .html
#     cache: false

#   # Static resources reloading during development
#   web:
#     resources:
#       static-locations: classpath:/static/

#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 10MB

server:
 port: 8000

spring:

  # konfigurasi untuk koneksi db
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver

    driver-class-name: com.mysql.jdbc.Driver

    # # sesuaikan nama database anda dengan di bawah ini
    # url: jdbc:mysql://containers-us-west-93.railway.app:6158/railway

    # # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    # username: root
    # password: t2BpsZqxtQnjgxHplIkQ

    # sesuaikan nama database anda dengan di bawah ini
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12601078?useSSL=false&serverTimezone=Asia/Jakarta

    # sesuaikan dengan NAMA dan PASSWORD anda dengan username password di bawah ini
    username: sql12601078
    password: FSusXBtcVN

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    # pembuatan database (create || create-drop || validate || update)
    hibernate.ddl-auto: update
    show-sql: true


  # # Templates reloading during development
  # thymeleaf:
  #   prefix: classpath:/templates/
  #   suffix: .html
  #   cache: false

  # # Static resources reloading during development
  # web:
  #   resources:
  #     static-locations: classpath:/static/

  # servlet:
  #   multipart:
  #     max-file-size: 10MB
  #     max-request-size: 10MB

